[package]
name = "tex"
version = "0.0.0"
edition = "2021"

[profile.release]
strip = true

[dependencies]
anyhow = "1.0.82"
async-recursion = "1.1.0"
axum = "0.7.5"
thiserror = "1.0.59"
tokio = { version = "1.37.0", features = ["full"] }
