FROM node:20.7.0-bookworm-slim AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN --mount=type=cache,target=/root/.npm npm ci
COPY client client
COPY render/preamble.tex render/
RUN npm run build

FROM nginx:1.25.2-bookworm
COPY --from=build /app/dist /etc/nginx/public
COPY proxy /etc/nginx/
