services:
  proxy:
    build:
      dockerfile: Dockerfile.proxy
    volumes:
      - ./data/proxy:/var/nginx
    ports:
      - 3000:80
  web:
    build:
      dockerfile: Dockerfile.web
    environment:
      RENDER_ENDPOINT: render:5000
  render:
    build:
      dockerfile: Dockerfile.render
    privileged: true
