name: build
on:
  push:
    branches:
      - main
jobs:
  proxy:
    runs-on: ubuntu-22.04
    steps:
      - uses: docker/setup-qemu-action@v3.0.0
        with:
          image: tonistiigi/binfmt:qemu-v7.0.0
      - uses: docker/setup-buildx-action@v3.3.0
        with:
          driver-opts: image=moby/buildkit
      - uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: docker/build-push-action@v5.3.0
        with:
          push: true
          provenance: false
          file: Dockerfile.proxy
          tags: ghcr.io/${{ github.repository }}/proxy,ghcr.io/${{ github.repository }}/proxy:sha-${{ github.sha }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
  web:
    runs-on: ubuntu-22.04
    steps:
      - uses: docker/setup-qemu-action@v3.0.0
        with:
          image: tonistiigi/binfmt:qemu-v7.0.0
      - uses: docker/setup-buildx-action@v3.3.0
        with:
          driver-opts: image=moby/buildkit
      - uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: docker/build-push-action@v5.3.0
        with:
          push: true
          provenance: false
          file: Dockerfile.web
          tags: ghcr.io/${{ github.repository }}/web,ghcr.io/${{ github.repository }}/web:sha-${{ github.sha }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
  render:
    runs-on: ubuntu-22.04
    steps:
      - uses: docker/setup-qemu-action@v3.0.0
        with:
          image: tonistiigi/binfmt:qemu-v7.0.0
      - uses: docker/setup-buildx-action@v3.3.0
        with:
          driver-opts: image=moby/buildkit
      - uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: docker/build-push-action@v5.3.0
        with:
          push: true
          provenance: false
          file: Dockerfile.render
          tags: ghcr.io/${{ github.repository }}/render,ghcr.io/${{ github.repository }}/render:sha-${{ github.sha }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
