name: Publish
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: docker/setup-buildx-action@v2.5.0
        with:
          driver-opts: image=moby/buildkit
      - uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: docker/build-push-action@v4.0.0
        with:
          push: true
          provenance: false
          tags: ghcr.io/${{ github.repository }},ghcr.io/${{ github.repository }}:sha-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
