name: Publish
on:
  push:
    branches:
      - main
jobs:
  web:
    runs-on: ubuntu-22.04
    steps:
      - uses: docker/setup-buildx-action@v2.5.0
        with:
          driver-opts: image=moby/buildkit
      - uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: docker/build-push-action@v4.0.0
        with:
          push: true
          provenance: false
          file: Dockerfile.web
          tags: ghcr.io/ginkoid/tex/web,ghcr.io/ginkoid/tex/web:sha-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  render:
    runs-on: ubuntu-22.04
    steps:
      - uses: docker/setup-buildx-action@v2.5.0
        with:
          driver-opts: image=moby/buildkit
      - uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: docker/build-push-action@v4.0.0
        with:
          push: true
          provenance: false
          file: Dockerfile.render
          tags: ghcr.io/ginkoid/tex/render,ghcr.io/ginkoid/tex/render:sha-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
